[build]
dir = "."
cmd = "templ generate && go build -o ./tmp/main.exe ./dev/main.go"
bin = "./tmp/main.exe"
include_ext = ["go", "templ", "sass"]
exclude_dir = ["tmp", "node_modules"]
exclude_regex = [".*_templ.go"]

stop_on_error = true

[build.before]
cmds = ["echo 'Hello'"]

# Windows-specific settings
kill_on_delay = "500ms"
delay = 1000

[screen]
clear_on_rebuild = true